# Generated by Django 3.0.4 on 2020-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id_processo', models.AutoField(primary_key=True, serialize=False)),
                ('processo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'processos',
                'managed': True,
            },
        ),
    ]
