# Generated by Django 3.0.4 on 2020-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id_tamanho', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tamanho',
                'managed': True,
            },
        ),
    ]
