# Generated by Django 3.0.4 on 2020-03-26 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamento', '0001_initial'),
        ('Centro_de_custo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('senha', models.CharField(blank=True, max_length=45, null=True)),
                ('login', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('adm', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
                ('id_centrocusto', models.ForeignKey(db_column='id_centrocusto', on_delete=django.db.models.deletion.DO_NOTHING, to='Centro_de_custo.CentroCusto')),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='Departamento.Departamento')),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vinculos',
            fields=[
                ('id_vinculos', models.AutoField(primary_key=True, serialize=False)),
                ('id_cc', models.ForeignKey(blank=True, db_column='id_cc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Centro_de_custo.CentroCusto')),
                ('id_dpto', models.ForeignKey(blank=True, db_column='id_dpto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Departamento.Departamento')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='_Login.Pessoa')),
            ],
            options={
                'db_table': 'vinculos',
                'managed': True,
            },
        ),
    ]
