# Generated by Django 3.0.5 on 2020-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'managed': True, 'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_contratacao',
            field=models.DateField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
