# Generated by Django 3.0.5 on 2020-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Login', '0002_auto_20200422_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListarPessoas',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('login', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('adm', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(max_length=255)),
                ('centro_custo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ListarPessoas',
                'managed': False,
            },
        ),
    ]
