"""
Django settings for _MyScrumWEB project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&=yk8&=d7=x0xw^wg^nwrj8#r-hc9n$&fh8^^!i2wzp+=hwspu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SECURE_SSL_REDIRECT  =  True

ALLOWED_HOSTS = ['www.myscrum.com.br','myscrum.com.br', 'www.nwtecnologia.com', 'nwtecnologia.com', 'localhost', '192.168.1.164', '192.168.1.211', 'www.ecxnez.hospedagemelastica.com.br', 'ecxnez.hospedagemelastica.com.br', '192.168.10.059']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    '_Base',
    '_Login',
    'Centro_de_custo',
    'Calendario',
    'Departamento',
    'Etapa',
    'Feriado',
    'Home',
    'Espelho',
    'Entregachaves',
    'Kanban',
    'Processo',
    'Retrospectiva',
    'Sub_etapa',
    'Tamanho',
    'Tarefa',
    'Solicitacao',    
    'Fluxo',
    'Dashboards',
    #App django para widgets
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_MyScrumWEB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_MyScrumWEB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myscrum',
        'USER': 'myscrum',
        'PASSWORD': 'nwdev2020',
        'HOST': 'mysql.myscrum1.kinghost.net',
        #'HOST': 'mysql.myscrum.com.br',   # Or an IP Address that your DB is hosted on
        #'NAME': 'nwtecnologia',
        #'USER': 'nwtecnologia',
        #'PASSWORD': 'nwdev2020',
        #'HOST': 'mysql.nwtecnologia.com',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }, 
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/myscrum/www/static/'

MEDIA_URL = '/media/'

# localhost
MEDIA_ROOT = (
    os.path.join(BASE_DIR, "media")
)

# Servidor de produção
# MEDIA_ROOT = '/home/myscrum/www/media/'

