# Generated by Django 3.0.4 on 2020-03-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Centro_de_custo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('etapa', models.CharField(blank=True, max_length=60, null=True)),
                ('id_cc', models.ForeignKey(db_column='id_cc', on_delete=django.db.models.deletion.DO_NOTHING, to='Centro_de_custo.CentroCusto')),
            ],
            options={
                'db_table': 'etapas',
                'managed': True,
            },
        ),
    ]
