# Generated by Django 2.2 on 2020-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefa', '0002_listartarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='retrospectiva',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
