# Generated by Django 2.2 on 2020-08-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_Login', '0002_auto_20200422_1556'),
        ('Tarefa', '0005_auto_20200709_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiva',
            name='id_update',
            field=models.ForeignKey(db_column='id_update', default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rupdater', to='_Login.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrospectiva',
            name='last_update',
            field=models.DateTimeField(default=3),
            preserve_default=False,
        ),
    ]
