# Generated by Django 2.2 on 2020-08-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefa', '0006_auto_20200805_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrospectiva',
            name='id_update',
            field=models.ForeignKey(db_column='id_update', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rUpdater', to='_Login.Pessoa'),
        ),
    ]
