# Generated by Django 2.2 on 2020-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefa', '0010_auto_20200813_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
