# Generated by Django 2.2 on 2020-08-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_Login', '0003_listarpessoas'),
        ('Tarefa', '0011_tarefa_data_finalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiva',
            name='id_responsavel',
            field=models.ForeignKey(db_column='id_responsavel', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_responsavel', to='_Login.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retrospectiva',
            name='id_update',
            field=models.ForeignKey(db_column='id_update', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_update', to='_Login.Pessoa'),
        ),
    ]
