# Generated by Django 2.2 on 2020-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefa', '0012_auto_20200825_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiva',
            name='r_historico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
