# Generated by Django 2.2 on 2020-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefa', '0013_retrospectiva_r_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiva',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
