# Generated by Django 3.0.4 on 2020-03-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEtapas',
            fields=[
                ('id_sub_etapas', models.AutoField(primary_key=True, serialize=False)),
                ('sub_etapa', models.CharField(blank=True, max_length=45, null=True)),
                ('id_etapa', models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.DO_NOTHING, to='Etapa.Etapas')),
            ],
            options={
                'db_table': 'sub_etapas',
                'managed': True,
            },
        ),
    ]
