from django.db import models
from Centro_de_custo.models import CentroCusto
from Tamanho.models import Tamanho
from Departamento.models import Departamento
from Processo.models import Processos
from _Login.models import Pessoa
from Tarefa.models import Tarefa, Executor

# Create your models here.

class FluxoSAT(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    prioridade = models.IntegerField(blank=True, null=True)
    stat = models.CharField(max_length=20, blank=True, null=True)
    porcentagem = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    processo_relacionado = models.IntegerField(blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    id_solicitacao = models.IntegerField(blank=True, null=True)
    empreendimento = models.CharField(max_length=50)
    bloco = models.CharField(max_length=20)
    unidade = models.CharField(max_length=10)
    proprietario_nome = models.CharField(max_length=100, blank=True, null=True)
    proprietario_email = models.CharField(max_length=100, blank=True, null=True)
    telefone1 = models.CharField(max_length=200, blank=True, null=True)
    status_processo = models.CharField(max_length=20)
    status_solicitacao = models.TextField(blank=True, null=True)
    data_entrega = models.DateField(blank=True, null=True)
    tipo_solicitacao = models.CharField(max_length=20, blank=True, null=True)
    ambiente = models.CharField(max_length=50)
    descricao_sat = models.TextField(blank=True, null=True)
    tipo_reparo = models.CharField(max_length=50)
    procedencia = models.CharField(max_length=50)
    historico_sat = models.TextField(blank=True, null=True)
    estimativa_custo = models.CharField(max_length=50)
    duracao = models.CharField(max_length=50)
    material = models.TextField(blank=True, null=True)
    finalizado = models.IntegerField(blank=True, null=True)
    id_status = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'FluxoSAT'

class FluxoLocacao(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    prioridade = models.IntegerField(blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    stat = models.CharField(max_length=20, blank=True, null=True)
    porcentagem = models.IntegerField(blank=True, null=True)
    prazo = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    id_status = models.IntegerField(blank=True, null=True)
    id_locacao = models.IntegerField(blank=True, null=True)
    lBloco = models.CharField(max_length=20)
    lUnidade = models.CharField(max_length=10)
    
    class Meta:
        managed = True
        db_table = 'FluxoLocacao'

class Juridico(models.Model):
    id_juridico = models.AutoField(primary_key=True)
    id_tarefa = models.IntegerField(blank=True, null=True)
    autor_assistente = models.CharField(max_length=200, blank=True, null=True)
    autor_advogado = models.CharField(max_length=200, blank=True, null=True)
    reu_assistente = models.CharField(max_length=200, blank=True, null=True)
    reu_advogado = models.CharField(max_length=200, blank=True, null=True)
    escritorio = models.CharField(max_length=200, blank=True, null=True)
    escritorio_advogado = models.CharField(max_length=200, blank=True, null=True)
    preposto = models.CharField(max_length=200, blank=True, null=True)
    resumo_processo = models.CharField(max_length=200, blank=True, null=True)
    numero_processo = models.CharField(max_length=200, blank=True, null=True)
    prazo_interno = models.DateField(blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True)
    valor_estimado = models.CharField(max_length=200, blank=True, null=True)
    valor_causa = models.CharField(max_length=200, blank=True, null=True)
    valor_acordo = models.CharField(max_length=200, blank=True, null=True)
    perito = models.CharField(max_length=200, blank=True, null=True)
    preposto = models.CharField(max_length=200, blank=True, null=True)
    jUnidade = models.CharField(max_length=45, blank=True, null=True)
    jBloco = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'juridico'

class Testemunhas(models.Model):
    id_testemunha = models.AutoField(primary_key=True)
    testemunha1 = models.CharField(max_length=45, blank=True, null=True)
    testemunha2 = models.CharField(max_length=45, blank=True, null=True)
    testemunha3 = models.CharField(max_length=45, blank=True, null=True)
    testemunha4 = models.CharField(max_length=45, blank=True, null=True)
    testemunha5 = models.CharField(max_length=45, blank=True, null=True)
    testemunha6 = models.CharField(max_length=45, blank=True, null=True)
    testemunha7 = models.CharField(max_length=45, blank=True, null=True)
    testemunha8 = models.CharField(max_length=45, blank=True, null=True)
    testemunha9 = models.CharField(max_length=45, blank=True, null=True)
    testemunha10 = models.CharField(max_length=45, blank=True, null=True)
    id_tarefa = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'testemunhas'

class Autor(models.Model):
    id_autor = models.AutoField(primary_key=True)
    autor1 = models.CharField(max_length=45, blank=True, null=True)
    autor2 = models.CharField(max_length=45, blank=True, null=True)
    autor3 = models.CharField(max_length=45, blank=True, null=True)
    autor4 = models.CharField(max_length=45, blank=True, null=True)
    autor5 = models.CharField(max_length=45, blank=True, null=True)
    autor6 = models.CharField(max_length=45, blank=True, null=True)
    autor7 = models.CharField(max_length=45, blank=True, null=True)
    autor8 = models.CharField(max_length=45, blank=True, null=True)
    autor9 = models.CharField(max_length=45, blank=True, null=True)
    autor10 = models.CharField(max_length=45, blank=True, null=True)
    id_tarefa = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'autor'

class Reu(models.Model):
    id_reu = models.AutoField(primary_key=True)
    reu1 = models.CharField(max_length=45, blank=True, null=True)
    reu2 = models.CharField(max_length=45, blank=True, null=True)
    reu3 = models.CharField(max_length=45, blank=True, null=True)
    reu4 = models.CharField(max_length=45, blank=True, null=True)
    reu5 = models.CharField(max_length=45, blank=True, null=True)
    reu6 = models.CharField(max_length=45, blank=True, null=True)
    reu7 = models.CharField(max_length=45, blank=True, null=True)
    reu8 = models.CharField(max_length=45, blank=True, null=True)
    reu9 = models.CharField(max_length=45, blank=True, null=True)
    reu10 = models.CharField(max_length=45, blank=True, null=True)
    id_tarefa = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'reu'

class Advocacia(models.Model):
    id_advocacia = models.AutoField(primary_key=True)
    escritorio = models.CharField(max_length=100, blank=True, null=True)
    id_empresa = models.IntegerField(blank=True, null=True)
    
    class Meta:
        managed = True
        db_table = 'advocacia'

class FluxoJuridico(models.Model):
    id_juridico = models.IntegerField(blank=True, null=True)
    id_status = models.IntegerField(blank=True, null=True)
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    prioridade = models.IntegerField(blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    stat = models.CharField(max_length=20, blank=True, null=True)
    porcentagem = models.IntegerField(blank=True, null=True)
    prazo = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    autor_assistente = models.CharField(max_length=200, blank=True, null=True)
    autor_advogado = models.CharField(max_length=200, blank=True, null=True)
    reu_assistente = models.CharField(max_length=200, blank=True, null=True)
    reu_advogado = models.CharField(max_length=200, blank=True, null=True)
    escritorio = models.CharField(max_length=200, blank=True, null=True)
    preposto = models.CharField(max_length=200, blank=True, null=True)
    resumo_processo = models.CharField(max_length=200, blank=True, null=True)
    numero_processo = models.CharField(max_length=200, blank=True, null=True)
    prazo_interno = models.DateField(blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True)
    valor_estimado = models.CharField(max_length=200, blank=True, null=True)
    valor_causa = models.CharField(max_length=200, blank=True, null=True)
    valor_acordo = models.CharField(max_length=200, blank=True, null=True)
    perito = models.CharField(max_length=200, blank=True, null=True)
    jUnidade = models.IntegerField(blank=True, null=True)
    jBloco = models.CharField(max_length=200, blank=True, null=True)
    autor1 = models.CharField(max_length=45, blank=True, null=True)
    autor2 = models.CharField(max_length=45, blank=True, null=True)
    autor3 = models.CharField(max_length=45, blank=True, null=True)
    autor4 = models.CharField(max_length=45, blank=True, null=True)
    autor5 = models.CharField(max_length=45, blank=True, null=True)
    autor6 = models.CharField(max_length=45, blank=True, null=True)
    autor7 = models.CharField(max_length=45, blank=True, null=True)
    autor8 = models.CharField(max_length=45, blank=True, null=True)
    autor9 = models.CharField(max_length=45, blank=True, null=True)
    autor10 = models.CharField(max_length=45, blank=True, null=True)
    reu1 = models.CharField(max_length=45, blank=True, null=True)
    reu2 = models.CharField(max_length=45, blank=True, null=True)
    reu3 = models.CharField(max_length=45, blank=True, null=True)
    reu4 = models.CharField(max_length=45, blank=True, null=True)
    reu5 = models.CharField(max_length=45, blank=True, null=True)
    reu6 = models.CharField(max_length=45, blank=True, null=True)
    reu7 = models.CharField(max_length=45, blank=True, null=True)
    reu8 = models.CharField(max_length=45, blank=True, null=True)
    reu9 = models.CharField(max_length=45, blank=True, null=True)
    reu10 = models.CharField(max_length=45, blank=True, null=True)
    testemunha1 = models.CharField(max_length=45, blank=True, null=True)
    testemunha2 = models.CharField(max_length=45, blank=True, null=True)
    testemunha3 = models.CharField(max_length=45, blank=True, null=True)
    testemunha4 = models.CharField(max_length=45, blank=True, null=True)
    testemunha5 = models.CharField(max_length=45, blank=True, null=True)
    testemunha6 = models.CharField(max_length=45, blank=True, null=True)
    testemunha7 = models.CharField(max_length=45, blank=True, null=True)
    testemunha8 = models.CharField(max_length=45, blank=True, null=True)
    testemunha9 = models.CharField(max_length=45, blank=True, null=True)
    testemunha10 = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'FluxoJuridico'

class Locacao(models.Model):
    id_locacao = models.AutoField(primary_key=True)
    id_tarefa = models.IntegerField(blank=True, null=True)
    lBloco = models.CharField(max_length=20, blank=True, null=True)
    lUnidade = models.CharField(max_length=10, blank=True, null=True)
    id_empresa = models.IntegerField(blank=True, null=True)
    
    class Meta:
        managed = True
        db_table = 'locacao'

class LocacaoEditar(models.Model):
    id_locacao_editar = models.AutoField(primary_key=True)
    descricao = models.TextField(blank=True, null=True)
    nome_coluna = models.CharField(max_length=255, blank=True, null=True)
    id_tamanho = models.ForeignKey(Tamanho, models.DO_NOTHING, db_column='id_tamanho', related_name='id_tamanho_locacao')
    prazo = models.IntegerField(blank=True, null=True)
    id_pendente_por = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_pendente_por', related_name='id_pendente_por',blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    id_departamento = models.ForeignKey(Departamento, models.DO_NOTHING, db_column='id_departamento', related_name='id_departamento_locacao')
    id_responsavel = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_responsavel', related_name='id_responsavel_locacao')
    id_autoridade = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_autoridade', related_name='id_autoridade_locacao')
    id_pessoa = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_pessoa', related_name='id_creator')
    last_update = models.DateTimeField(auto_now=True)
    id_update = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_update', related_name='id_updater')
    id_checado = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_checado', related_name='id_checado',blank=True, null=True)
    id_executor1 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor1', related_name='id_executor1')
    porcento1 = models.IntegerField(blank=True)
    id_executor2 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor2', related_name='id_executor2',blank=True, null=True)
    porcento2 = models.IntegerField(blank=True, null=True)
    id_executor3 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor3', related_name='id_executor3',blank=True, null=True)
    porcento3 = models.IntegerField(blank=True, null=True)
    id_executor4 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor4', related_name='id_executor4',blank=True, null=True)
    porcento4 = models.IntegerField(blank=True, null=True)
    id_executor5 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor5', related_name='is_executor5',blank=True, null=True)
    porcento5 = models.IntegerField(blank=True, null=True)
    id_executor6 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor6', related_name='id_executor6',blank=True, null=True)
    porcento6 = models.IntegerField(blank=True, null=True)
    id_executor7 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor7', related_name='id_executor7',blank=True, null=True)
    porcento7 = models.IntegerField(blank=True, null=True)
    id_executor8 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor8', related_name='id_executor8',blank=True, null=True)
    porcento8 = models.IntegerField(blank=True, null=True)
    id_executor9 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor9', related_name='id_executor9',blank=True, null=True)
    porcento9 = models.IntegerField(blank=True, null=True)
    id_executor10 = models.ForeignKey(Pessoa, models.DO_NOTHING, db_column='id_executor10', related_name='id_executor10',blank=True, null=True)
    porcento10 = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'locacao_editar'

class LocacaoConservacao(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    prioridade = models.IntegerField(blank=True, null=True)
    stat = models.CharField(max_length=20, blank=True, null=True)
    porcentagem = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    processo_relacionado = models.IntegerField(blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    status_processo = models.CharField(max_length=20, blank=True, null=True)
    id_status = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'FluxoLocacaoConservacao'

class MedicaoTerceiros(models.Model):
    id_medicao_terceiros = models.AutoField(primary_key=True)
    id_tarefa = models.IntegerField(blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    valor_bruto = models.CharField(max_length=20, blank=True, null=True)
    valor_liquido = models.CharField(max_length=20, blank=True, null=True)
    permuta = models.IntegerField(blank=True, null=True)
    
    class Meta:
        managed = True
        db_table = 'medicao_terceiro'

class FluxoMedicaoTerceiros(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    prioridade = models.IntegerField(blank=True, null=True)
    stat = models.CharField(max_length=20, blank=True, null=True)
    porcentagem = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    processo_relacionado = models.IntegerField(blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    id_medicao_terceiros = models.IntegerField(blank=True, null=True)
    id_medicao = models.IntegerField(blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    valor_bruto = models.CharField(max_length=20, blank=True, null=True)
    valor_liquido = models.CharField(max_length=20, blank=True, null=True)
    permuta = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'FluxoMedicaoTerceiros'

class ExportarLocacao(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    prioridade = models.IntegerField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    stat = models.CharField(max_length=20, blank=True, null=True)
    tamanho = models.CharField(max_length=255)
    porcentagem = models.IntegerField(blank=True, null=True)
    prazo = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_real = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    porcento1 = models.IntegerField(blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    porcento2 = models.IntegerField(blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    porcento3 = models.IntegerField(blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    porcento4 = models.IntegerField(blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    porcento5 = models.IntegerField(blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    porcento6 = models.IntegerField(blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    porcento7 = models.IntegerField(blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    porcento8 = models.IntegerField(blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    porcento9 = models.IntegerField(blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    porcento10 = models.IntegerField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField()
    historico = models.TextField()
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    etapa = models.CharField(max_length=255)
    subetapa = models.CharField(max_length=255)
    processo_relacionado = models.CharField(max_length=255)
    predecessor_1 = models.IntegerField(blank=True, null=True)
    predecessor_2 = models.IntegerField(blank=True, null=True)
    predecessor_3 = models.IntegerField(blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    r5w2hT = models.IntegerField(blank=True, null=True)
    id_locacao = models.IntegerField(blank=True, null=True)
    id_status = models.IntegerField(blank=True, null=True)
    lBloco = models.CharField(max_length=45, blank=True, null=True)
    lUnidade = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'ExportarLocacao'

class ExportarMedicao(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    descri = models.TextField(blank=True, null=True)
    prioridade = models.IntegerField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    stat = models.CharField(max_length=20, blank=True, null=True)
    tamanho = models.CharField(max_length=255)
    porcentagem = models.IntegerField(blank=True, null=True)
    prazo = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_real = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    porcento1 = models.IntegerField(blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    porcento2 = models.IntegerField(blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    porcento3 = models.IntegerField(blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    porcento4 = models.IntegerField(blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    porcento5 = models.IntegerField(blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    porcento6 = models.IntegerField(blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    porcento7 = models.IntegerField(blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    porcento8 = models.IntegerField(blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    porcento9 = models.IntegerField(blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    porcento10 = models.IntegerField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField()
    historico = models.TextField()
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    etapa = models.CharField(max_length=255)
    subetapa = models.CharField(max_length=255)
    processo_relacionado = models.CharField(max_length=255)
    predecessor_1 = models.IntegerField(blank=True, null=True)
    predecessor_2 = models.IntegerField(blank=True, null=True)
    predecessor_3 = models.IntegerField(blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    r5w2hT = models.IntegerField(blank=True, null=True)
    id_medicao_terceiros = models.IntegerField(blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    valor_bruto = models.CharField(max_length=20, blank=True, null=True)
    valor_liquido = models.CharField(max_length=20, blank=True, null=True)
    permuta = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'ExportarMedicao'