# Generated by Django 3.1.2 on 2020-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departamento', '0002_auto_20200818_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imagem',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
