from django.db import models
from Centro_de_custo.models import CentroCusto
from Tamanho.models import Tamanho
from Departamento.models import Departamento
from Processo.models import Processos
from _Login.models import Pessoa
from Tarefa.models import Tarefa, Executor

# Create your models here.

class Solicitacao(models.Model):
    id_solicitacao = models.AutoField(primary_key=True)
    id_empresa = models.IntegerField(blank=True, null=True)
    id_tarefa = models.ForeignKey(Tarefa, models.DO_NOTHING, db_column='id_tarefa')
    empreendimento = models.CharField(max_length=50, blank=True, null=True)
    bloco = models.CharField(max_length=20, blank=True, null=True)
    unidade = models.CharField(max_length=10, blank=True, null=True)
    proprietario_nome = models.CharField(max_length=100, blank=True, null=True)
    proprietario_rg = models.CharField(max_length=20, blank=True, null=True)
    proprietario_cpf = models.CharField(max_length=20, blank=True, null=True)
    proprietario_email = models.CharField(max_length=100, blank=True, null=True)
    solicitante_nome = models.CharField(max_length=100, blank=True, null=True)
    solicitante_rg = models.CharField(max_length=20, blank=True, null=True)
    solicitante_cpf = models.CharField(max_length=20, blank=True, null=True)
    solicitante_email = models.CharField(max_length=100, blank=True, null=True)
    telefone1 = models.CharField(max_length=200, blank=True, null=True)
    telefone2 = models.CharField(max_length=200, blank=True, null=True)
    status_processo = models.CharField(max_length=20, blank=True, null=True)
    status_solicitacao = models.TextField(blank=True, null=True)
    data_abertura = models.DateField(blank=True, null=True)
    data_atendimento = models.DateField(blank=True, null=True)
    data_finalizacao_sat = models.DateField(blank=True, null=True)
    data_entrega = models.DateField(blank=True, null=True)
    tipo_solicitacao = models.CharField(max_length=20, blank=True, null=True)
    tempo_total = models.IntegerField(blank=True, null=True)
    satisfacao_avaliacao = models.IntegerField(blank=True, null=True)
    satisfacao_observacoes = models.TextField(blank=True, null=True)
    pessoa_quitacao = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'solicitacao'

class Problema(models.Model):
    id_problema = models.AutoField(primary_key=True)
    id_solicitacao = models.ForeignKey(Solicitacao, models.DO_NOTHING, db_column='id_solicitacao')
    ambiente = models.CharField(max_length=20, blank=True, null=True)
    descricao_sat = models.CharField(max_length=1000, blank=True, null=True)
    tipo_reparo = models.CharField(max_length=20, blank=True, null=True)
    raiz = models.CharField(max_length=100, blank=True, null=True)
    procedencia = models.CharField(max_length=20, blank=True, null=True)
    historico_sat = models.TextField(blank=True, null=True)
    estimativa_custo = models.CharField(max_length=200, blank=True, null=True)
    duracao = models.FloatField(blank=True, null=True)
    material = models.TextField(blank=True, null=True)
    finalizado = models.IntegerField(blank=True, null=True)
    data_inicial_p = models.DateField(blank=True, null=True)
    data_final_p = models.DateField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'problema'

class ListarSolicitacoes(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    id_empresa = models.IntegerField(blank=True, null=True)
    descri = models.TextField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    prioridade = models.IntegerField(blank=True, null=True)
    stat = models.CharField(max_length=20, blank=True, null=True)
    porcentagem = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_real = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    status_pendencia = models.TextField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    departamento = models.CharField(max_length=255)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    checado = models.CharField(max_length=45, blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    id_solicitacao = models.IntegerField(blank=True, null=True)
    empreendimento = models.CharField(max_length=50)
    bloco = models.CharField(max_length=20)
    unidade = models.CharField(max_length=10)
    proprietario_nome = models.CharField(max_length=100, blank=True, null=True)
    proprietario_rg = models.CharField(max_length=20, blank=True, null=True)
    proprietario_cpf = models.CharField(max_length=20, blank=True, null=True)
    proprietario_email = models.CharField(max_length=100, blank=True, null=True)
    solicitante_nome = models.CharField(max_length=100, blank=True, null=True)
    solicitante_rg = models.CharField(max_length=20, blank=True, null=True)
    solicitante_cpf = models.CharField(max_length=20, blank=True, null=True)
    solicitante_email = models.CharField(max_length=100, blank=True, null=True)
    telefone1 = models.CharField(max_length=200, blank=True, null=True)
    telefone2 = models.CharField(max_length=200, blank=True, null=True)
    status_processo = models.CharField(max_length=20)
    status_solicitacao = models.TextField(blank=True, null=True)
    data_entrega = models.DateField(blank=True, null=True)
    tipo_solicitacao = models.CharField(max_length=20, blank=True, null=True)
    tempo_total = models.IntegerField(blank=True, null=True)
    satisfacao_avaliacao = models.IntegerField(blank=True, null=True)
    satisfacao_observacoes = models.TextField(blank=True, null=True)
    pessoa_quitacao = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ListarSolicitacoes'

class ExportarSolicitacoes(models.Model):
    id_tarefa = models.AutoField(primary_key=True)
    id_empresa = models.IntegerField(blank=True, null=True)
    descri = models.TextField(blank=True, null=True)
    prioridade = models.IntegerField(blank=True, null=True)
    centro_custo = models.CharField(max_length=255)
    stat = models.CharField(max_length=20, blank=True, null=True)
    tamanho = models.CharField(max_length=255)
    porcentagem = models.IntegerField(blank=True, null=True)
    prazo = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_real = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao = models.DateField(blank=True, null=True)
    executor1 = models.CharField(max_length=45, blank=True, null=True)
    porcento1 = models.IntegerField(blank=True, null=True)
    executor2 = models.CharField(max_length=45, blank=True, null=True)
    porcento2 = models.IntegerField(blank=True, null=True)
    executor3 = models.CharField(max_length=45, blank=True, null=True)
    porcento3 = models.IntegerField(blank=True, null=True)
    executor4 = models.CharField(max_length=45, blank=True, null=True)
    porcento4 = models.IntegerField(blank=True, null=True)
    executor5 = models.CharField(max_length=45, blank=True, null=True)
    porcento5 = models.IntegerField(blank=True, null=True)
    executor6 = models.CharField(max_length=45, blank=True, null=True)
    porcento6 = models.IntegerField(blank=True, null=True)
    executor7 = models.CharField(max_length=45, blank=True, null=True)
    porcento7 = models.IntegerField(blank=True, null=True)
    executor8 = models.CharField(max_length=45, blank=True, null=True)
    porcento8 = models.IntegerField(blank=True, null=True)
    executor9 = models.CharField(max_length=45, blank=True, null=True)
    porcento9 = models.IntegerField(blank=True, null=True)
    executor10 = models.CharField(max_length=45, blank=True, null=True)
    porcento10 = models.IntegerField(blank=True, null=True)
    pendente_por = models.CharField(max_length=45, blank=True, null=True)
    status_pendencia = models.TextField()
    historico = models.TextField()
    departamento = models.TextField(blank=True, null=True)
    responsavel = models.CharField(max_length=45, blank=True, null=True)
    autoridade = models.CharField(max_length=45, blank=True, null=True)
    processo_relacionado = models.CharField(max_length=255)
    checado = models.CharField(max_length=45, blank=True, null=True)
    id_solicitacao = models.IntegerField(blank=True, null=True)
    empreendimento = models.CharField(max_length=255, blank=True, null=True)
    bloco = models.CharField(max_length=255)
    unidade = models.CharField(max_length=255)
    proprietario_nome = models.CharField(max_length=255)
    proprietario_rg = models.CharField(max_length=255)
    proprietario_cpf = models.CharField(max_length=255)
    proprietario_email = models.CharField(max_length=255)
    solicitante_nome = models.CharField(max_length=255)
    solicitante_rg = models.CharField(max_length=255)
    solicitante_cpf = models.CharField(max_length=255)
    solicitante_email = models.CharField(max_length=255)
    telefone1 = models.CharField(max_length=255)
    telefone2 = models.CharField(max_length=255)
    status_processo = models.CharField(max_length=50)
    status_solicitacao = models.CharField(max_length=50)
    data_entrega = models.DateField(blank=True, null=True)
    tipo_solicitacao = models.CharField(max_length=50)
    tempo_total = models.CharField(max_length=50)
    satisfacao_avaliacao = models.CharField(max_length=50)
    satisfacao_observacoes = models.CharField(max_length=255)
    finalizado = models.IntegerField(blank=True, null=True)
    ambiente = models.CharField(max_length=50)
    descricao_sat = models.TextField()
    tipo_reparo = models.CharField(max_length=50)
    procedencia = models.CharField(max_length=50)
    historico_sat = models.TextField()
    estimativa_custo = models.CharField(max_length=50)
    duracao = models.CharField(max_length=50)
    material = models.TextField()
    data_inicial_p = models.DateField(blank=True, null=True)
    data_final_p = models.DateField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'ExportarSolicitacoes'

class DashboardSAT(models.Model):
    stat = models.CharField(max_length=20, blank=True, null=True)
    id_tarefa = models.AutoField(primary_key=True)
    id_empresa = models.IntegerField(blank=True, null=True)
    data_ini = models.DateField(blank=True, null=True)
    data_fim = models.DateField(blank=True, null=True)
    data_finalizacao_sat = models.DateField(blank=True, null=True)
    id_solicitacao = models.IntegerField(blank=True, null=True)
    empreendimento = models.CharField(max_length=50)
    status_processo = models.CharField(max_length=20)
    tipo_reparo = models.CharField(max_length=50)
    satisfacao_avaliacao = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'DashboardSAT'